{"name": "Проверка, что нельзя создать двух одинаковых курьеров.", "status": "passed", "description": "Успешное создание одного курьера, попытка создания второго курьера с теми же учётными данными,проверка получения статуса кода 409 и сообщения об ошибке.", "steps": [{"name": "Создаем курьера", "status": "passed", "start": 1734214406679, "stop": 1734214407036}, {"name": "Создаем курьера", "status": "passed", "start": 1734214407036, "stop": 1734214407391}], "start": 1734214406679, "stop": 1734214407391, "uuid": "6591151d-8ef2-4a3d-a56a-9fb3e96e29e8", "historyId": "6832e863dd6d182e4787cc90d059c7da", "testCaseId": "6832e863dd6d182e4787cc90d059c7da", "fullName": "tests.couriers.test_create_courier.TestCreateCourier#test_create_two_couriers", "labels": [{"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "3192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_create_courier"}]}